"use strict";

export const users = [
  {
    id: 1,
    name: "Cliff Lovelock",
    age: 34,
    email: "clovelock0@de.vu",
    country: "Indonesia",
    company: "Twitterlist",
    birthday: "16-11-1987",
  },
  {
    id: 2,
    name: "Holden Croyser",
    age: 25,
    email: "hcroyser1@census.gov",
    country: "Namibia",
    company: "Quinu",
    birthday: "23-04-1998",
  },
  {
    id: 3,
    name: "Jaquelin Daniele",
    age: 25,
    email: "jdaniele2@patch.com",
    country: "France",
    company: "Dabjam",
    birthday: "11-01-1998",
  },
  {
    id: 4,
    name: "Yehudi Talby",
    age: 32,
    email: "ytalby3@opensource.org",
    country: "Czech Republic",
    company: "Twitterwire",
    birthday: "21-11-1989",
  },
  {
    id: 5,
    name: "Rodina Bardnam",
    age: 31,
    email: "rbardnam4@eventbrite.com",
    country: "Uruguay",
    company: "Linktype",
    birthday: "25-09-1990",
  },
  {
    id: 6,
    name: "Eli Rice",
    age: 26,
    email: "erice5@hhs.gov",
    country: "Philippines",
    company: "Devify",
    birthday: "06-04-1997",
  },
  {
    id: 7,
    name: " Barrie Vaz",
    age: 21,
    email: "bvaz6@yahoo.com",
    country: "France",
    company: "Trunyx",
    birthday: "27-08-2000",
  },
  {
    id: 8,
    name: " Page Andrzejczak",
    age: 31,
    email: "pandrzejczak7@lulu.com",
    country: "Sri Lanka",
    company: "Leenti",
    birthday: "02-10-1990",
  },
  {
    id: 9,
    name: "Maddie Lowne",
    age: 22,
    email: "mlowne8@google.com.hk",
    country: "Indonesia",
    company: "Edgewire",
    birthday: "02-01-2000",
  },
  {
    id: 10,
    name: "Julius Rickardes",
    age: 29,
    email: "jrickardes9@boston.com",
    country: "China",
    company: "Oyondu",
    birthday: "21-06-1992",
  },
];
